config:
  plugins:
    metrics-by-endpoint: {}
  target: 'http://localhost:3000'
  phases:
    - duration: 10
      arrivalRate: 1
scenarios:
  - name: "Sessions Flow (register + login)"
    flow:
      - log: "Creating variables for user" # Vamos
      - log: "test user"
      - get:
          url: '/api/session/api/test/user'
          capture:
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.age"
              as: "age"
            - json: "$.password"
              as: "password"
            - json: "$.role"
              as: "role"
            - json: "$.carts"
              as: "carts"
      - log: "Verifying values from test/user endpoint"
      - log: "Registering user"
      - post:
          url: "/api/session/register"
          json: #Vamos a recibir las variables de nuestro script generador de usuarios
            first_name: "{{ first_name }}"
            last_name: "{{ last_name }}"
            email: "{{ email }}"
            age: "{{age}}"
            password: "{{ password }}"
            role: "{{ role }}"
            # carts: "{{ carts }}"
      - think: 2
      - log: "Login user"
      - post:
          url: "/api/session/login"
          json:
            email: "{{ email }}"
            password: "{{ password }}"