paths:
  /products/:
    get:
      summary: Obtener todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Todos los productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        "500":
          description: Error interno del servidor
    post:
      summary: Crear producto
      tags:
        - Producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/ProductCreation"
      responses:
        "200":
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/products"
        "500":
          description: Error interno del servidor
  /products/{id}:
    get:
      summary: Obtener todos los productos
      tags:
        - Productos
      parameters:
        - name: id
          in: path
          required: true
          description: el id del producto
          schema:
           $type: string
      responses:
         "200":
          description:  producto obtenido correctamente
          content:
            application/json:
              schema:
                $ref: "#components/schemas/products"
    delete:
      summary: Eliminar producto
      tags:
        - Producto
      parameters:
        - name: id
          in: path
          required: true
          description: el id del producto
          schema:
           $type: string
      responses:
         "200":
          description:  producto eliminado
          content:
            application/json:
              schema:
                $ref: "#components/schemas/products"
         "404":
          description: Producto no encontrado
components:
  schemas:
    products:
      type: object
      properties:
        _id:
         type: ObjectId
         description: id del producto generado automaticamente
        title:
         type: string
         description: Titulo del producto
        description:
         type: string
         description: Descripcion del producto
        code:
         type: number
         description: Codigo unico
        price:
         type: number
         description: Precio
        status:
         type: boolean
         description: Status
        stock:
         type: number
         description: Stock de productos
        category:
         type: string
         description: Categoria
        thumbnail:
         type: string
         description: Thumbnail
      example:
        _id: ObjectId("60c72b2f5f1b2c001f8e4b23")
        title: "amoladora"
        description: "amoladora stanley"
        code: 23
        price: 20000
        status: true
        stock: 2
        category: "Ferreteria"
    ProductCreation:
      type: object
      properties:
        title:
         type: string
         description: Titulo del producto
        description:
         type: string
         description: Descripcion del producto
        code:
         type: number
         description: Codigo unico
        price:
         type: number
         description: Precio
        status:
         type: boolean
         description: Status
        stock:
         type: number
         description: Stock de productos
        category:
         type: string
         description: Categoria
        thumbnail:
         type: string
         description: Thumbnail
